name: todo application infra setup
on:
  workflow_dispatch:
  pull_request:
    branches: main
  push:
    branches: main

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  TF_DIR: environments/dev
  ARM_USE_OIDC: "true"
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4          

      - name: Terraform Version
        run: terraform --version

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_DIR }}

      - name: Upload tfplan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_DIR }}/tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: self-hosted
    environment: pre-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4          

      - name: Download tfplan Artifact
        uses: actions/download-artifact@v4  
        with:
          name: tfplan
          path: ${{ env.TF_DIR }}

      - name: Terraform Init
        run: terraform init                 
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_DIR }}
